/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/mo.glb --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.configurator003.geometry} material={nodes.configurator003.material} position={[-184.632, 151.49, 75.712]} rotation={[0, 0.873, 0]} scale={4.676} />
      <mesh geometry={nodes.base.geometry} material={nodes.base.material} position={[-58.65, 150.746, 9.6]} scale={356.061} />
      <mesh geometry={nodes.bbrv.geometry} material={nodes.bbrv.material} position={[-248.191, 166.704, -149.722]} rotation={[Math.PI, -1.536, Math.PI]} scale={[6.216, 8.202, 6.216]} />
      <mesh geometry={nodes.display_board.geometry} material={nodes.display_board.material} position={[-131.666, 177.577, 64.177]} rotation={[0, -0.702, 0]} scale={[1.649, 19.099, 2.446]} />
      <mesh geometry={nodes.road.geometry} material={nodes.road.material} position={[57.692, 152.369, 69.15]} rotation={[Math.PI, -1.516, Math.PI]} scale={[-22.882, -103.602, -23.889]} />
      <mesh geometry={nodes.turf.geometry} material={nodes.turf.material} position={[-222.044, 168.092, 260.742]} rotation={[-Math.PI / 2, 0, 0]} scale={[152.069, 4.788, 4.455]} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[150.796, 152.086, -232.975]} rotation={[1.578, -0.036, 1.032]} scale={[64.628, 56.461, 51.37]} />
      <mesh geometry={nodes.projector_screen.geometry} material={nodes.projector_screen.material} position={[194.315, 163.656, 281.801]} rotation={[0, 1.562, 1.571]} scale={[-27.516, -65.159, -27.516]} />
      <mesh geometry={nodes.couch.geometry} material={nodes.couch.material} position={[89.267, 159.587, 279.353]} rotation={[-2.923, 1.53, -1.788]} scale={8.798} />
      <mesh geometry={nodes.github.geometry} material={nodes.github.material} position={[94.512, 161.988, -76.712]} rotation={[1.417, -0.336, 1.057]} scale={128.79} />
      <mesh geometry={nodes.socialtrees.geometry} material={nodes.socialtrees.material} position={[243.107, 184.631, 20.563]} rotation={[-Math.PI, 0.652, -Math.PI]} scale={[7.07, 9.673, 6.057]} />
      <mesh geometry={nodes.instagram.geometry} material={nodes.instagram.material} position={[97.837, 164.119, -305.67]} rotation={[0, 0, 1.373]} scale={-127.176} />
      <mesh geometry={nodes.linkedin.geometry} material={nodes.linkedin.material} position={[231.84, 158.625, 22.233]} rotation={[1.452, -0.317, 0.918]} scale={142.56} />
      <mesh geometry={nodes.trees.geometry} material={nodes.trees.material} position={[-341.939, 184.638, -316.289]} rotation={[-Math.PI, 0.652, -Math.PI]} scale={[7.07, 9.673, 6.057]} />
      <mesh geometry={nodes.configurator004.geometry} material={nodes.configurator004.material} position={[-225.776, 150.879, 86.279]} scale={4.676} />
      <mesh geometry={nodes.configurator001.geometry} material={nodes.configurator001.material} position={[-272.177, 151.619, 84.197]} scale={4.676} />
      <mesh geometry={nodes.configurator002.geometry} material={nodes.configurator002.material} position={[-311.63, 152.42, 73.967]} rotation={[0, -0.753, 0]} scale={4.676} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[-222.463, 156.446, 259.231]} scale={[151.462, 76.548, 87.458]} />
      <mesh geometry={nodes.Books.geometry} material={nodes.Books.material} position={[-251.178, 170.746, -73.334]} rotation={[-0.003, -0.044, 0.008]} scale={19.551} />
      <mesh geometry={nodes.chair.geometry} material={nodes.chair.material} position={[-260.011, 160.858, -67.147]} rotation={[-Math.PI, 0.118, -Math.PI]} scale={13.325} />
      <mesh geometry={nodes.charger.geometry} material={nodes.charger.material} position={[-270.448, 161.349, -76.165]} scale={[0.459, 0.459, 1.32]} />
      <mesh geometry={nodes.clock.geometry} material={nodes.clock.material} position={[-257.63, 185.603, -82.558]} rotation={[-1.565, 0, 0]} scale={[2.952, 0.181, 2.952]} />
      <mesh geometry={nodes.clockhourneedle.geometry} material={nodes.clockhourneedle.material} position={[-258.565, 185.993, -82.508]} rotation={[-1.684, -1.012, -0.016]} scale={[0.196, 1.164, 0.982]} />
      <mesh geometry={nodes.clockminuteneedle.geometry} material={nodes.clockminuteneedle.material} position={[-257.605, 186.944, -82.508]} rotation={[-1.571, 0.017, -0.017]} scale={[0.226, 1.164, 1.447]} />
      <mesh geometry={nodes.clockrotationaxis.geometry} material={nodes.clockrotationaxis.material} position={[-257.67, 185.556, -82.449]} rotation={[1.568, 0, 0]} scale={[0.396, 0.076, 0.396]} />
      <mesh geometry={nodes.flowerpot.geometry} material={nodes.flowerpot.material} position={[-278.146, 162.774, -76.311]} scale={1.784} />
      <mesh geometry={nodes.laptop.geometry} material={nodes.laptop.material} position={[-260.193, 169.758, -75.826]} scale={[3.355, 3.047, 3.047]} />
      <mesh geometry={nodes.Phone.geometry} material={nodes.Phone.material} position={[-264.663, 169.766, -75.597]} rotation={[-Math.PI, 0, 0]} scale={[-0.667, -0.985, -1.256]} />
      <mesh geometry={nodes.photoframe1.geometry} material={nodes.photoframe1.material} position={[-277.814, 186.371, -81.896]} rotation={[1.611, 0, 0]} scale={[1.2, 1.002, 1.811]} />
      <mesh geometry={nodes.photoframe1001.geometry} material={nodes.photoframe1001.material} position={[-268.047, 186.371, -81.896]} rotation={[1.611, 0, 0]} scale={[1.2, 1.002, 1.811]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-273.292, 163.598, -82.949]} rotation={[1.686, 0, 0]} scale={[1.663, 1.676, 2.473]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-261.334, 193.672, -82.828]} rotation={[1.563, 0, 0]} scale={[11.262, 1, 0.479]} />
      <mesh geometry={nodes.plant.geometry} material={nodes.plant.material} position={[-278.21, 169.238, -76.083]} rotation={[-Math.PI, 0, 0]} scale={[-0.239, -6.741, -0.26]} />
      <mesh geometry={nodes.Room.geometry} material={nodes.Room.material} position={[-261.044, 156.479, -66.5]} scale={[20.806, 20.082, 19.476]} />
      <mesh geometry={nodes['slippers&mouse'].geometry} material={nodes['slippers&mouse'].material} position={[-263.786, 161.441, -75.547]} rotation={[0, 0.803, -3.132]} scale={[-1.764, -0.152, -0.926]} />
      <mesh geometry={nodes.table.geometry} material={nodes.table.material} position={[-259.667, 169.474, -75.611]} />
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-242.209, 179.164, -70.449]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[2.776, 2.161, 2.72]} />
      <mesh geometry={nodes.windowsides.geometry} material={nodes.windowsides.material} position={[-241.566, 191.878, -72.789]} scale={[1, 1.038, 0.709]} />
      <mesh geometry={nodes.woodfloor.geometry} material={nodes.woodfloor.material} position={[-262.176, 159.97, -64.757]} scale={[-19.196, -16.889, -17.745]} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[14.916, 150.81, 103.695]} scale={5.01} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-362.638, 150.81, -25.619]} scale={5.01} />
      <mesh geometry={nodes.chair003.geometry} material={nodes.chair003.material} position={[-363.623, 152.367, -117.21]} rotation={[0, 0, -Math.PI]} scale={[-1.045, -3.485, -2.643]} />
      <mesh geometry={nodes.chair004.geometry} material={nodes.chair004.material} position={[-129.074, 152.367, -140.727]} rotation={[-Math.PI, 0, 0]} scale={[-1.045, -3.485, -2.643]} />
      <mesh geometry={nodes.chair007.geometry} material={nodes.chair007.material} position={[-290.086, 152.367, -259.193]} rotation={[0, -1.282, -Math.PI]} scale={[-1.772, -3.485, -2.643]} />
      <mesh geometry={nodes.chair005.geometry} material={nodes.chair005.material} position={[-92.142, 152.367, -259.193]} rotation={[0, -1.282, -Math.PI]} scale={[-1.772, -3.485, -2.643]} />
      <mesh geometry={nodes.chair006.geometry} material={nodes.chair006.material} position={[-329.041, 152.367, 119.256]} rotation={[Math.PI, -1.369, 0]} scale={[-1.772, -3.485, -2.643]} />
      <mesh geometry={nodes.chair008.geometry} material={nodes.chair008.material} position={[-52.932, 152.367, 125.507]} rotation={[0, -1.003, -Math.PI]} scale={[-1.772, -3.485, -2.643]} />
      <mesh geometry={nodes.chair001.geometry} material={nodes.chair001.material} position={[-363.623, 152.367, -58.6]} rotation={[0, 0, -Math.PI]} scale={[-1.045, -3.485, -2.643]} />
      <mesh geometry={nodes.chair002.geometry} material={nodes.chair002.material} position={[-129.074, 152.367, -82.366]} rotation={[-Math.PI, 0, 0]} scale={[-1.045, -3.485, -2.643]} />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[-362.638, 150.81, -188.257]} scale={5.01} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-135.827, 150.81, -187.37]} scale={5.01} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[-132.459, 150.81, -27.12]} scale={5.01} />
    </group>
  )
}

useGLTF.preload('/mo.glb')
