/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model/finalroom.glb 
*/

import React from 'react'
import { Html, MeshReflectorMaterial, useGLTF } from '@react-three/drei'
import  { useEffect, useRef, useState } from 'react'
import { Float,  useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { Selection, Select, EffectComposer, Outline } from '@react-three/postprocessing'
import useSound from 'use-sound';
import hover from '/sounds/hover.mp3';
import { FaSun } from "react-icons/fa";
import { FaMoon } from "react-icons/fa";
import { useFrame, useThree } from '@react-three/fiber'
import './BlendMaterial.jsx' // registers the custom material
import { RigidBody } from '@react-three/rapier'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/finalroom.glb')



    const [hovered, setHovered] = useState(false)
    const [photoFrame1Hovered, setPhotoFrame1Hovered] = useState(false)
    const [textHovered, setTextHovered] = useState(false)
    const [chargerHovered, setChargerHovered] = useState(false)
    const [photoFrame1001Hovered, setPhotoFrame1001Hovered] = useState(false)
  
    const videoTextureRef = useRef()
    const [play,{stop}] = useSound(hover);
    const isNight=props.isNight;
    const setIsNight=props.setIsNight;

    useEffect(() => {
      const video = document.createElement('video')
      video.src = '/videos/static.mp4'
      video.crossOrigin = 'Anonymous'
      video.loop = true
      video.muted = true
      video.playsInline = true
      video.autoplay = true
      video.play()
    
      const texture = new THREE.VideoTexture(video)
      texture.flipY = false
      texture.colorSpace = THREE.SRGBColorSpace
    
      videoTextureRef.current = texture
    }, [])
  

    const mixRef = useRef(0.0)
    

const blendMatsRef = useRef([])   // ← collect all material instances here

useFrame((_, delta) => {
  const target = isNight ? 1.0 : 0.0
  mixRef.current = THREE.MathUtils.lerp(mixRef.current, target, delta * 0.5)

  // directly update every registered material
  blendMatsRef.current.forEach((mat) => {
    if (mat) mat.uniforms.mixRatio.value = mixRef.current
  })
})



 // ================== DAY TEXTURES ==================
const D_base = useTexture('/textures/Room/Day/base.png')
D_base.flipY = false
D_base.colorSpace = THREE.SRGBColorSpace

const D_ballphoto = useTexture('/textures/Room/Day/D_ballphoto_bake.webp')
D_ballphoto.flipY = false
D_ballphoto.colorSpace = THREE.SRGBColorSpace

const D_book = useTexture('/textures/Room/Day/D_book_bake.webp')
D_book.flipY = false
D_book.colorSpace = THREE.SRGBColorSpace

const D_chair = useTexture('/textures/Room/Day/D_Chair_bake.webp')
D_chair.flipY = false
D_chair.colorSpace = THREE.SRGBColorSpace

const D_cup = useTexture('/textures/Room/Day/D_cup_bake.webp')
D_cup.flipY = false
D_cup.colorSpace = THREE.SRGBColorSpace

const D_flowerpot = useTexture('/textures/Room/Day/D_flowerpot_bake.webp')
D_flowerpot.flipY = false
D_flowerpot.colorSpace = THREE.SRGBColorSpace

const D_laptop = useTexture('/textures/Room/Day/D_laptop_bake.webp')
D_laptop.flipY = false
D_laptop.colorSpace = THREE.SRGBColorSpace

const D_snm = useTexture('/textures/Room/Day/D_s&m_bake.webp')
D_snm.flipY = false
D_snm.colorSpace = THREE.SRGBColorSpace

const D_table = useTexture('/textures/Room/Day/D_table_bake.webp')
D_table.flipY = false
D_table.colorSpace = THREE.SRGBColorSpace

const D_woodfloor = useTexture('/textures/Room/Day/D_woodfloor_bake.webp')
D_woodfloor.flipY = false
D_woodfloor.colorSpace = THREE.SRGBColorSpace

const D_plant = useTexture('/textures/Room/Day/Day_plant_bake.webp')
D_plant.flipY = false
D_plant.colorSpace = THREE.SRGBColorSpace

const D_shelves = useTexture('/textures/Room/Day/Day_shelves_texture.webp')
D_shelves.flipY = false
D_shelves.colorSpace = THREE.SRGBColorSpace

const D_walls = useTexture('/textures/Room/Day/Day_walls_bake.webp')
D_walls.flipY = false
D_walls.colorSpace = THREE.SRGBColorSpace

const light = useTexture('/textures/Room/Day/light_bake.webp')
light.flipY = false
light.colorSpace = THREE.SRGBColorSpace


// ================== NIGHT TEXTURES ==================
const N_base = useTexture('/textures/Room/Night/N_base_bake_1.webp')
N_base.flipY = false
N_base.colorSpace = THREE.SRGBColorSpace

const N_ballphoto = useTexture('/textures/Room/Night/N_ballphoto_bake.webp')
N_ballphoto.flipY = false
N_ballphoto.colorSpace = THREE.SRGBColorSpace

const N_book = useTexture('/textures/Room/Night/N_book_bake.webp')
N_book.flipY = false
N_book.colorSpace = THREE.SRGBColorSpace

const N_chair = useTexture('/textures/Room/Night/N_Chair_bake.webp')
N_chair.flipY = false
N_chair.colorSpace = THREE.SRGBColorSpace

const N_cup = useTexture('/textures/Room/Night/N_cup_bake.webp')
N_cup.flipY = false
N_cup.colorSpace = THREE.SRGBColorSpace

const N_flowerpot = useTexture('/textures/Room/Night/N_flowerpot_bake.webp')
N_flowerpot.flipY = false
N_flowerpot.colorSpace = THREE.SRGBColorSpace

const N_laptop = useTexture('/textures/Room/Night/N_laptop_bake_1.webp')
N_laptop.flipY = false
N_laptop.colorSpace = THREE.SRGBColorSpace

const N_plant = useTexture('/textures/Room/Night/N_plant_bake.webp')
N_plant.flipY = false
N_plant.colorSpace = THREE.SRGBColorSpace

const N_snm = useTexture('/textures/Room/Night/N_s&m_bake.webp')
N_snm.flipY = false
N_snm.colorSpace = THREE.SRGBColorSpace

const N_table = useTexture('/textures/Room/Night/N_table_bake.webp')
N_table.flipY = false
N_table.colorSpace = THREE.SRGBColorSpace

const N_walls = useTexture('/textures/Room/Night/N_walls_bake_v2.webp')
N_walls.flipY = false
N_walls.colorSpace = THREE.SRGBColorSpace

const N_woodfloor = useTexture('/textures/Room/Night/N_woodenfloor_bake.webp')
N_woodfloor.flipY = false
N_woodfloor.colorSpace = THREE.SRGBColorSpace

const N_shelves = useTexture('/textures/Room/Night/M_shelves_bake.webp')
N_shelves.flipY = false
N_shelves.colorSpace = THREE.SRGBColorSpace




  return (
  <>
    <Html position={[-1.3,0.52,0]} >
      <button onClick={() => setIsNight(prev => !prev)}>
        {isNight ? <FaSun size={32} className='fill-amber-600' /> : <FaMoon size={32} className='fill-gray-600'/>}
      </button>
    </Html>

    <group {...props} dispose={null}>
     
        <Float rotationIntensity={0} speed={3.1} floatIntensity={1} floatingRange={[1, 3]} >

        <mesh geometry={nodes.Plane001.geometry} position={[-0.29, 42.128, -22.673]} rotation={[1.563, 0, 0]} scale={[11.262, 1, 0.479]}>
          <meshBasicMaterial map={light} />
        </mesh>

        <mesh geometry={nodes.windowsides.geometry} position={[19.478, 40.334, -12.634]} scale={[1, 1.038, 0.709]}>
          <blendMaterial map={D_shelves} map2={N_shelves} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>
     <RigidBody type='fixed' colliders='cuboid'>
        <mesh geometry={nodes.Room.geometry} position={[0, 4.935, -6.344]} scale={[20.806, 20.082, 19.476]}>
            <blendMaterial
    map={D_walls}
    map2={N_walls}
    ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}
  />
        </mesh>
        </RigidBody>

        <mesh geometry={nodes.table.geometry} position={[1.377, 17.93, -15.456]}>
          <blendMaterial map={D_table} map2={N_table} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <mesh geometry={nodes.laptop.geometry} position={[0.851, 18.214, -15.67]} scale={[3.355, 3.047, 3.047]}>
          <blendMaterial map={D_laptop} map2={N_laptop} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <mesh position={[0.851, 21.214, -18.45]} scale={[6.355, 4.047, 3.047]}>
          <planeGeometry args={[1, 1]} />
          {videoTextureRef.current && (
            <meshBasicMaterial
              map={videoTextureRef.current}
              toneMapped={false}
            />
          )}
        </mesh>

        <Select enabled={hovered}>
          <mesh
            onPointerOver={(e) => {e.stopPropagation();play();setHovered(true);}}
            onPointerOut={(e) => {e.stopPropagation();stop();setHovered(false);}}
            geometry={nodes.Phone.geometry}
            material={materials.phn}
            position={[-3.619, 18.222, -15.442]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.667, -0.985, -1.256]}
          />
        </Select>

        <mesh geometry={nodes.Books.geometry} position={[9.866, 19.202, -13.179]} rotation={[-0.003, -0.044, 0.008]} scale={19.551}>
          <blendMaterial map={D_book} map2={N_book} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <mesh geometry={nodes.CoffeeCup.geometry} position={[-7.528, 18.237, -15.827]} scale={16.224}>
          <blendMaterial map={D_cup} map2={N_cup} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <mesh geometry={nodes['slippers&mouse'].geometry} position={[-2.742, 9.897, -15.391]} rotation={[0, 0.803, -3.132]} scale={[-1.764, -0.152, -0.926]}>
          <blendMaterial map={D_snm} map2={N_snm} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <mesh geometry={nodes.flowerpot.geometry} position={[-17.102, 11.23, -16.155]} scale={1.784}>
          <blendMaterial map={D_flowerpot} map2={N_flowerpot} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <mesh geometry={nodes.plant.geometry} position={[-17.166, 17.694, -15.928]} rotation={[-Math.PI, 0, 0]} scale={[-0.239, -6.741, -0.26]}>
          <blendMaterial map={D_plant} map2={N_plant} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <Select enabled={photoFrame1Hovered}>
          <mesh
            onPointerOver={(e) => { e.stopPropagation(); play(); setPhotoFrame1Hovered(true); }}
            onPointerOut={(e) => { e.stopPropagation(); stop(); setPhotoFrame1Hovered(false); }}
            geometry={nodes.photoframe1.geometry}
            position={[-16.77, 34.827, -21.741]}
            rotation={[1.611, 0, 0]}
            scale={[1.2, 1.002, 1.811]}
          >
            <blendMaterial map={D_ballphoto} map2={N_ballphoto} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
          </mesh>
        </Select>

        <mesh geometry={nodes.clock.geometry} material={materials.clock} position={[3.414, 34.059, -22.403]} rotation={[-1.565, 0, 0]} scale={[2.952, 0.181, 2.952]} />
        <mesh geometry={nodes.clockhourneedle.geometry} material={nodes.clockhourneedle.material} position={[2.479, 34.449, -22.353]} rotation={[-1.684, -1.012, -0.016]} scale={[0.196, 1.164, 0.982]} />
        <mesh geometry={nodes.clockminuteneedle.geometry} material={nodes.clockminuteneedle.material} position={[3.439, 35.4, -22.353]} rotation={[-1.571, 0.017, -0.017]} scale={[0.226, 1.164, 1.447]} />
        <mesh geometry={nodes.clockrotationaxis.geometry} material={materials.CLOCKCIRCLR} position={[3.374, 34.012, -22.294]} rotation={[1.568, 0, 0]} scale={[0.396, 0.076, 0.396]} />

        <mesh geometry={nodes.woodfloor.geometry} position={[-1.132, 8.426, -4.601]} scale={[-19.196, -16.889, -17.745]}>
          <blendMaterial map={D_woodfloor} map2={N_woodfloor} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <mesh geometry={nodes.chair.geometry} position={[1.033, 9.314, -6.991]} rotation={[-Math.PI, 0.118, -Math.PI]} scale={13.325}>
          <blendMaterial map={D_chair} map2={N_chair} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

        <Select enabled={textHovered}>
          <mesh
            onPointerOver={(e) => { e.stopPropagation(); play(); setTextHovered(true); }}
            onPointerOut={(e) => { e.stopPropagation(); stop(); setTextHovered(false); }}
            geometry={nodes.Text.geometry}
            position={[18.835, 27.62, -10.293]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[2.776, 2.161, 2.72]}
          >
            <meshStandardMaterial emissive="purple" emissiveIntensity={2} />
          </mesh>
        </Select>

        <group position={[-12.247, 12.054, -22.793]} rotation={[1.686, 0, 0]} scale={[1.663, 1.676, 2.473]}>
          <mesh geometry={nodes.Plane018.geometry} material={materials.socket} />
          <mesh geometry={nodes.Plane018_1.geometry} material={materials.inner} />
        </group>

        <Select enabled={chargerHovered}>
          <mesh
            onPointerOver={(e) => { e.stopPropagation(); play(); setChargerHovered(true); }}
            onPointerOut={(e) => { e.stopPropagation(); stop(); setChargerHovered(false); }}
            geometry={nodes.charger.geometry}
            material={materials['Material.015']}
            position={[-9.404, 9.805, -16.009]}
            scale={[0.459, 0.459, 1.32]}
          />
        </Select>


        <mesh geometry={nodes.photoframe1001.geometry} position={[-7.003, 34.827, -21.741]} rotation={[1.611, 0, 0]} scale={[1.2, 1.002, 1.811]}>
          <blendMaterial map={D_ballphoto} map2={N_ballphoto} ref={(mat) => { if (mat) blendMatsRef.current.push(mat) }}/>
        </mesh>

      </Float>
        <group position={[-22.57, 1.902, 136.243]} scale={4.676}>
          <mesh geometry={nodes.Plane004.geometry} material={materials.config} />
          <mesh geometry={nodes.Plane004_1.geometry} material={materials.configcomp} />
        </group>

        <group position={[-4.903, 1.902, 136.243]} scale={4.676}>
          <mesh geometry={nodes.Plane001_1.geometry} material={materials.config} />
          <mesh geometry={nodes.Plane001_2.geometry} material={materials.configcomp} />
        </group>

        <group position={[15.169, 1.902, 136.243]} scale={4.676}>
          <mesh geometry={nodes.Plane002.geometry} material={materials.config} />
          <mesh geometry={nodes.Plane002_1.geometry} material={materials.configcomp} />
        </group>

        <group position={[33.121, 1.902, 136.243]} scale={4.676}>
          <mesh geometry={nodes.Plane007.geometry} material={materials.config} />
          <mesh geometry={nodes.Plane007_1.geometry} material={materials.configcomp} />
        </group>
        <RigidBody type='fixed' colliders='trimesh'>
      <mesh geometry={nodes.base.geometry} position={[-0.206, 1.405, -0.409]} scale={[-210.376, -300.508, -300.376]}> 
  
      </mesh>
      </RigidBody>
     
     
        

    </group>
  </>
)
}

useGLTF.preload('/model/finalroom.glb')
