/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/room.glb 
*/

import React, { useEffect, useRef, useState } from 'react'
import { Float,  useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { Selection, Select, EffectComposer, Outline } from '@react-three/postprocessing'
import useSound from 'use-sound';
import hover from '/sounds/hover.mp3';

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/room.glb')
   const [hovered, setHovered] = useState(false)
   const [blankphotoframehovered,setBlankPhotoFrameHovered]=useState(false)
   const [ballonhillphotoframehovered,setBallOnHillPhotoFrameHovered]=useState(false)
   const videoTextureRef = useRef()
    const [play,{stop}] = useSound(hover);


useEffect(() => {
  const video = document.createElement('video')
  video.src = '/videos/static.mp4'
  video.crossOrigin = 'Anonymous'
  video.loop = true
  video.muted = true
  video.playsInline = true
  video.autoplay = true
  video.play()

  const texture = new THREE.VideoTexture(video)
  texture.flipY = false
  texture.colorSpace = THREE.SRGBColorSpace

  videoTextureRef.current = texture
}, [])
    const baseTexture=useTexture('/textures/bakedbase.webp')
    baseTexture.flipY=false
    baseTexture.colorSpace=THREE.SRGBColorSpace
  
    const wallTexture=useTexture('/textures/bakewalls.webp')
    wallTexture.flipY=false
    wallTexture.colorSpace=THREE.SRGBColorSpace
  
    
    const tableTexture=useTexture('/textures/bakedtable.webp')
    tableTexture.flipY=false
    tableTexture.colorSpace=THREE.SRGBColorSpace
  
     const shelvesTexture=useTexture('/textures/bakedshelves.webp')
    shelvesTexture.flipY=false
    shelvesTexture.colorSpace=THREE.SRGBColorSpace
  
    const woodTexture=useTexture('/textures/bakedwoodenfloor.webp')
    woodTexture.flipY=false
    woodTexture.colorSpace=THREE.SRGBColorSpace
  
      const snmTexture=useTexture('/textures/slippers&mousebake.webp')
    snmTexture.flipY=false
    snmTexture.colorSpace=THREE.SRGBColorSpace
  
    
      const clockTexture=useTexture('/textures/clcokbake.webp')
    clockTexture.flipY=false
    clockTexture.colorSpace=THREE.SRGBColorSpace
  
     const plantTexture=useTexture('/textures/plant.webp')
    plantTexture.flipY=false
    plantTexture.colorSpace=THREE.SRGBColorSpace
  
    
     const potTexture=useTexture('/textures/plantbase.webp')
    potTexture.flipY=false
    potTexture.colorSpace=THREE.SRGBColorSpace
  
    const laptopTexture=useTexture('/textures/bakedlaptop.webp')
    laptopTexture.flipY=false
    laptopTexture.colorSpace=THREE.SRGBColorSpace

     const configTexture=useTexture('/textures/configbake.webp')
    configTexture.flipY=false
    configTexture.colorSpace=THREE.SRGBColorSpace
  return (
    <group {...props} dispose={null}>
      <group>
         <Float rotationIntensity={0} speed={3.1} floatIntensity={1} floatingRange={[1, 3]} >
          <mesh geometry={nodes.Plane001.geometry} material={materials.light} position={[-0.29, 42.128, -22.673]} rotation={[1.563, 0, 0]} scale={[11.262, 1, 0.479]} />
      <mesh geometry={nodes.windowsides.geometry}  position={[19.478, 40.334, -12.634]} scale={[1, 1.038, 0.709]} ><meshBasicMaterial map={shelvesTexture}/></mesh>
      <mesh geometry={nodes.Room.geometry}  position={[0, 4.935, -6.344]} scale={[20.806, 20.082, 19.476]} ><meshBasicMaterial map={wallTexture}/></mesh>
      <mesh geometry={nodes.table.geometry}  position={[1.377, 17.93, -15.456]} ><meshBasicMaterial map={tableTexture}/></mesh>
      
        
      <mesh geometry={nodes.laptop.geometry} position={[0.851, 18.214, -15.67]} scale={[3.355, 3.047, 3.047]} ><meshBasicMaterial map={laptopTexture}/></mesh>
          
      <mesh position={[0.851, 21.214, -18.45]}   scale={[6.355, 4.047, 3.047]}>
  <planeGeometry args={[1, 1]} />
  {videoTextureRef.current && (
    <meshBasicMaterial
      map={videoTextureRef.current}
      toneMapped={false}
    />
  )}
</mesh>
      
      
       
      
 
    <Select enabled={hovered}>
      <group  onPointerOver={(e) => {e.stopPropagation();play();setHovered(true);}} onPointerOut={(e) => {e.stopPropagation();stop();setHovered(false);}} position={[-3.619, 18.222, -15.442]} rotation={[-Math.PI, 0, 0]} scale={[-0.667, -0.985, -1.256]} >
        <mesh geometry={nodes.Plane005.geometry} material={materials.phn} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials.phnscreen} />
      </group>
      </Select>
      <group position={[9.866, 19.202, -13.179]} rotation={[-0.003, -0.044, 0.008]} scale={19.551}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['book cover']} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['stacked paper']} />
      </group>
      <mesh geometry={nodes.CoffeeCup.geometry} material={materials.porcelain} position={[-7.528, 18.237, -15.827]} scale={16.224} />
      <mesh geometry={nodes['slippers&mouse'].geometry}  position={[-2.742, 9.897, -15.391]} rotation={[0, 0.803, -3.132]} scale={[-1.764, -0.152, -0.926]} ><meshBasicMaterial map={snmTexture}/></mesh>
      <mesh geometry={nodes.flowerpot.geometry}  position={[-17.102, 11.23, -16.155]} scale={1.784} ><meshBasicMaterial map={potTexture}/></mesh>
      
      <mesh geometry={nodes.plant.geometry}  position={[-17.166, 17.694, -15.928]} rotation={[-Math.PI, 0, 0]} scale={[-0.239, -6.741, -0.26]} ><meshBasicMaterial map={plantTexture}/></mesh>
      <Select enabled={ballonhillphotoframehovered}>
      <group  onPointerOver={(e) => {e.stopPropagation();play();setBallOnHillPhotoFrameHovered(true);}} onPointerOut={(e) => {e.stopPropagation();stop();setBallOnHillPhotoFrameHovered(false);}} position={[-16.77, 34.827, -21.741]} rotation={[1.611, 0, 0]} scale={[1.2, 1.002, 1.811]}>
        <mesh geometry={nodes.Plane013.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Plane013_1.geometry} material={materials.photosides} />
      </group>
      </Select>
      <Select enabled={blankphotoframehovered}>
      <group  onPointerOver={(e) => {e.stopPropagation(); play();setBlankPhotoFrameHovered(true);}} onPointerOut={(e) => {e.stopPropagation();stop();setBlankPhotoFrameHovered(false);}} position={[-6.477, 34.827, -21.741]} rotation={[1.611, 0, 0]} scale={[1.2, 1.002, 1.811]}>
        <mesh geometry={nodes.Plane014.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials.photosides} />
      </group>
      </Select>
      <mesh geometry={nodes.clock.geometry} material={materials.clock} position={[3.414, 34.059, -22.403]} rotation={[-1.565, 0, 0]} scale={[2.952, 0.181, 2.952]} ><meshBasicMaterial map={clockTexture}/></mesh>
      <mesh geometry={nodes.clockhourneedle.geometry}  position={[2.479, 34.449, -22.353]} rotation={[-1.684, -1.012, -0.016]} scale={[0.196, 1.164, 0.982]} ><meshStandardMaterial color="black"/></mesh>
      <mesh geometry={nodes.clockminuteneedle.geometry}  position={[3.439, 35.4, -22.353]} rotation={[-1.571, 0.017, -0.017]} scale={[0.226, 1.164, 1.447]} ><meshStandardMaterial color="black"/></mesh>
      <mesh geometry={nodes.clockrotationaxis.geometry} material={materials.CLOCKCIRCLR} position={[3.374, 34.012, -22.294]} rotation={[1.568, 0, 0]} scale={[0.396, 0.076, 0.396]} />
      <mesh geometry={nodes.woodfloor.geometry}  position={[-1.132, 8.426, -4.601]} scale={[-19.196, -16.889, -17.745]} ><meshBasicMaterial map={woodTexture}/></mesh>
      <mesh geometry={nodes.chair.geometry} material={materials['Chair 1']} position={[1.033, 9.314, -6.991]} rotation={[-Math.PI, 0.118, -Math.PI]} scale={13.325} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.008']} position={[18.835, 27.62, -10.293]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[2.776, 2.161, 2.72]} />
      <group position={[-12.247, 12.054, -22.793]} rotation={[1.686, 0, 0]} scale={[1.663, 1.676, 2.473]}>
        <mesh geometry={nodes.Plane018.geometry} material={materials.socket} />
        <mesh geometry={nodes.Plane018_1.geometry} material={materials.inner} />
      </group>
      <mesh geometry={nodes.chargernonbezier.geometry} material={materials['Material.015']} position={[-9.404, 9.805, -16.009]} scale={[0.459, 0.459, 1.32]} />
      <mesh geometry={nodes.chargerbezier.geometry} material={materials['Material.017']} position={[-9.339, 9.687, -14.684]} />
      <group position={[-3.84, 1.902, 136.243]} scale={4.676}>
        <mesh geometry={nodes.Plane021.geometry}  ><meshBasicMaterial map={configTexture}/></mesh>
        <mesh geometry={nodes.Plane021_1.geometry}  ><meshBasicMaterial map={configTexture}/></mesh>
      </group>
      <group position={[16.324, 1.902, 136.243]} scale={4.676}>
        <mesh geometry={nodes.Plane022.geometry} ><meshBasicMaterial map={configTexture}/></mesh>
        <mesh geometry={nodes.Plane022_1.geometry}  ><meshBasicMaterial map={configTexture}/></mesh>
      </group>
      <group position={[40.227, 1.902, 136.243]} scale={4.676}>
        <mesh geometry={nodes.Plane023.geometry}  ><meshBasicMaterial map={configTexture}/></mesh>
        <mesh geometry={nodes.Plane023_1.geometry}  ><meshBasicMaterial map={configTexture}/></mesh>
      </group>
      </Float>
    </group>
      <mesh geometry={nodes.base.geometry} material={materials.base} position={[-0.206, 1.405, -0.409]} scale={-300.376} />
    </group>
  )
}

useGLTF.preload('/model/room.glb')
