/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/spiderman.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Spiderman(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/model/spiderman.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[1.56, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Amazing_Spider-man_OBJ_mesh_Meshpart1Mtl_0" geometry={nodes['Amazing_Spider-man_OBJ_mesh_Meshpart1Mtl_0'].geometry} material={materials.Meshpart1Mtl} skeleton={nodes['Amazing_Spider-man_OBJ_mesh_Meshpart1Mtl_0'].skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/spiderman.glb')
